version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - "6868:8080"
    environment:
      - API_KEY=${API_KEY}
      - SPRING_APPLICATION_JSON={"spring.datasource.url":"jdbc:postgresql://postgresdb:5432/${POSTGRESDB_DATABASE}","spring.datasource.username":"${POSTGRESDB_USER}","spring.datasource.password":"${POSTGRESDB_ROOT_PASSWORD}","spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.PostgreSQLDialect","spring.jpa.hibernate.ddl-auto":"update"}
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
